[package]
name = "luno"
version = "0.2.0"
description = "An unofficial Rust wrapper for the Luno API."
authors = ["Duncan Dean <duncangleeddean@gmail.com>"]
edition = "2018"
license = "MIT"
documentation = "https://duncandean.github.io/luno-rust"
homepage = "https://github.com/duncandean/luno-rust"
repository = "https://github.com/duncandean/luno-rust"
readme = "README.md"
keywords = ["luno", "bitx"]

[dependencies]
reqwest = { version = "0.10.0-alpha.2", features = ["json"] }
futures = "0.3"
tokio = "0.2.0-alpha.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.41"
strum = "0.17.1"
strum_macros = "0.16.0"
