[package]
name = "luno"
version = "0.2.1"
description = "An unofficial Rust wrapper for the Luno API."
authors = ["Duncan Dean <duncangleeddean@gmail.com>"]
edition = "2018"
license = "MIT"
documentation = "https://duncandean.github.io/luno-rust"
homepage = "https://github.com/duncandean/luno-rust"
repository = "https://github.com/duncandean/luno-rust"
readme = "README.md"
keywords = ["luno", "bitx"]

[dependencies]
reqwest = { version = "0.10.4", features = ["json"] }
futures = "0.3.4"
tokio = { version = "0.2.13", features = ["macros"] }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.50"
strum = "0.18.0"
strum_macros = "0.18.0"
mockito = "0.25.0"
